line-length = 100
target-version = "py311"

# Don't lint historical v1.x — preserved for lineage only
exclude = [
  "src/v1.0",
  "src/v1.1",
  "src/v1.2",
  "src/v1.3",
  "src/v1.4"
]

[lint]
# Core rule sets
select = ["E", "F", "I"]
# Relax: module import placement + long lines (CSS/HTML strings, JSON templates)
ignore = ["E402", "E501"]
