name: Lint
on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Ruff
        run: pip install ruff
      - name: Ruff format (check only)
        run: ruff format --check .
      - name: Ruff check
        run: ruff check .
