name: Lint
on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff (format/check on v2.*)
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          paths=(src/v2.*)
          if (( ${#paths[@]} == 0 )); then
            echo "No v2.* directories found; skipping Ruff."
            exit 0
          fi
          echo "Linting paths: ${paths[*]}"
          ruff format --check "${paths[@]}"
          ruff check "${paths[@]}"
